### ISSUE TITLE
tulsi: within a Bazel generated temp directory ("/bazel-").

### ISSUE THREAD

**Issue by Jacky-LinPeng** [baveku/prozer-bazel#2]
make fetch
make build
tulsi get error:

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/15797691/176982141-f3e563ad-bd2f-4699-8533-717d56ad0e7f.png">

**Comment by baveku** [comment]
> make fetch
> 
> make build
> 
> tulsi get error:
> 
> 
> 
> <img width="1352" alt="image" src="https://user-images.githubusercontent.com/15797691/176982141-f3e563ad-bd2f-4699-8533-717d56ad0e7f.png">
> 
> 

What tulsi version do you use?
This template maybe outofdate from Bazel and Tulsi, I will update this soon.

**Comment by Jacky-LinPeng** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/15797691/176983872-74186036-050a-4a8a-8963-f2a49e747a29.png">

**Comment by Jacky-LinPeng** [comment]
> > make fetch
> > make build
> > tulsi get error:
> > <img alt="image" width="1352" src="https://user-images.githubusercontent.com/15797691/176982141-f3e563ad-bd2f-4699-8533-717d56ad0e7f.png">
> 
> What tulsi version do you use? This template maybe outofdate from Bazel and Tulsi, I will update this soon.

Hello, have you updated it?

**Comment by baveku** [comment]
> > > make fetch
> > > make build
> > > tulsi get error:
> > > <img alt="image" width="1352" src="https://user-images.githubusercontent.com/15797691/176982141-f3e563ad-bd2f-4699-8533-717d56ad0e7f.png">
> > 
> > 
> > What tulsi version do you use? This template maybe outofdate from Bazel and Tulsi, I will update this soon.
> 
> Hello, have you updated it?

I don't have time to fix it.
Tomorrow or Sunday, I will take time to upgrade Bazel and PodToBuild to latest version.

**Comment by Jacky-LinPeng** [comment]
> > > > make fetch
> > > > make build
> > > > tulsi get error:
> > > > <img alt="image" width="1352" src="https://user-images.githubusercontent.com/15797691/176982141-f3e563ad-bd2f-4699-8533-717d56ad0e7f.png">
> > > 
> > > 
> > > What tulsi version do you use? This template maybe outofdate from Bazel and Tulsi, I will update this soon.
> > 
> > 
> > Hello, have you updated it?
> 
> I don't have time to fix it. Tomorrow or Sunday, I will take time to upgrade Bazel and PodToBuild to latest version.

Thank you, your demo helped me a lot
